<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ArchUnitSharp.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArchUnitSharp.Common\ArchUnitSharp.Common.csproj" />
    <ProjectReference Include="..\ArchUnitSharp.Extraction\ArchUnitSharp.Extraction.csproj" />
    <ProjectReference Include="..\ArchUnitSharp.Files\ArchUnitSharp.Files.csproj" />
    <ProjectReference Include="..\ArchUnitSharp.Graph\ArchUnitSharp.Graph.csproj" />
    <ProjectReference Include="..\ArchUnitSharp.Layers\ArchUnitSharp.Layers.csproj" />
    <ProjectReference Include="..\ArchUnitSharp.Metrics\ArchUnitSharp.Metrics.csproj" />
    <ProjectReference Include="..\ArchUnitSharp.Slices\ArchUnitSharp.Slices.csproj" />
  </ItemGroup>

</Project>