using ArchUnitSharp.Metrics.Rendering;

namespace ArchUnitSharp.Metrics.Tests;

public class MetricsHtmlRendererTests
{
    private const string DefaultCss =
        ":root { color-scheme: light dark; font-family: system-ui, sans-serif; }\n"
        + "body { max-width: 960px; margin: 0 auto; padding: 2rem; }\n"
        + "h1 { margin-bottom: .25rem; }\n"
        + ".timestamp { color: #666; margin-top: 0; }\n"
        + "table { border-collapse: collapse; margin-top: 1.5rem; width: 100%; }\n"
        + "th, td { border: 1px solid #bbb; padding: .6rem .8rem; text-align: left; }\n"
        + "th { background: rgba(127, 127, 127, .14); }\n"
        + "tr:nth-child(even) { background: rgba(127, 127, 127, .07); }\n"
        + "footer { color: #666; font-size: .85rem; margin-top: 2rem; }";

    [Fact]
    public void Render_produces_the_whole_self_contained_page()
    {
        string html = MetricsHtmlRenderer.Render(
            new Dictionary<string, string>
            {
                ["method count [App.Car]"] = "1",
            },
            new MetricsExportOptions(),
            "2026-08-10T18:30:00Z");

        Assert.Equal(
            "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
            + "<meta charset=\"utf-8\">\n"
            + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
            + "<title>ArchUnitSharp Metrics Report</title>\n"
            + "<style>" + DefaultCss + "</style>\n"
            + "</head>\n<body>\n<main>\n"
            + "<h1>ArchUnitSharp Metrics Report</h1>\n"
            + "<p class=\"timestamp\">Generated: 2026-08-10T18:30:00Z</p>\n"
            + "<table>\n<thead><tr><th>Metric</th><th>Value</th></tr></thead>\n<tbody>\n"
            + "<tr><td>method count [App.Car]</td><td>1</td></tr>\n"
            + "</tbody>\n</table>\n</main>\n"
            + "<footer>Generated by ArchUnitSharp</footer>\n</body>\n</html>\n",
            html);
    }

    [Fact]
    public void Render_omits_the_timestamp_when_none_is_given()
    {
        string html = MetricsHtmlRenderer.Render(
            new Dictionary<string, string>(),
            new MetricsExportOptions { IncludeTimestamp = false },
            timestamp: null);

        Assert.DoesNotContain("Generated:", html);
        Assert.Contains("No metric data.", html);
    }

    [Fact]
    public void Render_escapes_the_title_the_keys_and_the_values()
    {
        string html = MetricsHtmlRenderer.Render(
            new Dictionary<string, string>
            {
                ["<script>alert(1)</script>"] = "<strong>7</strong>",
            },
            new MetricsExportOptions { Title = "Team <Metrics>", IncludeTimestamp = false },
            timestamp: null);

        Assert.Contains("<title>Team &lt;Metrics&gt;</title>", html);
        Assert.Contains("&lt;script&gt;alert(1)&lt;/script&gt;", html);
        Assert.Contains("&lt;strong&gt;7&lt;/strong&gt;", html);
        Assert.DoesNotContain("<script>alert(1)</script>", html);
        Assert.DoesNotContain("<strong>7</strong>", html);
    }

    [Fact]
    public void Render_neutralises_a_custom_stylesheet_that_tries_to_close_the_style_element()
    {
        string html = MetricsHtmlRenderer.Render(
            new Dictionary<string, string> { ["score"] = "2.5" },
            new MetricsExportOptions
            {
                IncludeTimestamp = false,
                CustomCss = "body { color: red; } </style><script>bad()</script>",
            },
            timestamp: null);

        Assert.Contains("body { color: red; }", html);
        Assert.Contains("<\\/style>", html);
        Assert.DoesNotContain("</style><script>", html);
    }

    [Fact]
    public void Render_orders_rows_by_key_whatever_the_map_yields()
    {
        string html = MetricsHtmlRenderer.Render(
            new Dictionary<string, string>
            {
                ["z metric"] = "1",
                ["a metric"] = "2",
            },
            new MetricsExportOptions { IncludeTimestamp = false },
            timestamp: null);

        int first = html.IndexOf("<td>a metric</td>", StringComparison.Ordinal);
        int second = html.IndexOf("<td>z metric</td>", StringComparison.Ordinal);
        Assert.True(first >= 0, "the first row is missing");
        Assert.True(second >= 0, "the second row is missing");
        Assert.True(first < second, "rows are not sorted by key");
    }

    [Fact]
    public void Render_uses_a_custom_stylesheet_in_place_of_the_default()
    {
        string html = MetricsHtmlRenderer.Render(
            new Dictionary<string, string>(),
            new MetricsExportOptions { IncludeTimestamp = false, CustomCss = "body { color: teal; }" },
            timestamp: null);

        Assert.Contains("<style>body { color: teal; }</style>", html);
        Assert.DoesNotContain(DefaultCss, html);
    }

    [Fact]
    public void Render_rejects_a_null_data_map()
    {
        Assert.Throws<ArgumentNullException>(() =>
            MetricsHtmlRenderer.Render(null!, new MetricsExportOptions(), timestamp: null));
    }

    [Fact]
    public void Render_rejects_null_options()
    {
        Assert.Throws<ArgumentNullException>(() =>
            MetricsHtmlRenderer.Render(new Dictionary<string, string>(), null!, timestamp: null));
    }
}
