using System.Text.RegularExpressions;
using ArchUnitSharp.Common.Extraction;

namespace ArchUnitSharp.Metrics.Tests;

public class MetricsExporterTests
{
    [Fact]
    public void ToHtml_renders_a_complete_escaped_report_with_a_utc_timestamp()
    {
        string html = MetricsExporter.ToHtml(new Dictionary<string, string>
        {
            ["<script>alert(1)</script>"] = "<strong>7</strong>",
        });

        Assert.StartsWith("<!DOCTYPE html>", html);
        Assert.Contains("<meta charset=\"utf-8\">", html);
        Assert.Contains("<title>ArchUnitSharp Metrics Report</title>", html);
        Assert.Contains("&lt;script&gt;alert(1)&lt;/script&gt;", html);
        Assert.Contains("&lt;strong&gt;7&lt;/strong&gt;", html);
        Assert.Matches(new Regex(@"Generated: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z"), html);
        Assert.Contains("Generated by ArchUnitSharp", html);
        Assert.DoesNotContain("<script>alert(1)</script>", html);
        Assert.DoesNotContain("<strong>7</strong>", html);
    }

    [Fact]
    public void ToHtml_supports_a_custom_title_and_css_and_omits_the_timestamp_on_request()
    {
        string html = MetricsExporter.ToHtml(
            new Dictionary<string, string> { ["score"] = "2.5" },
            new MetricsExportOptions
            {
                Title = "Team <Metrics>",
                IncludeTimestamp = false,
                CustomCss = "body { color: red; } </style><script>bad()</script>",
            });

        Assert.Contains("<title>Team &lt;Metrics&gt;</title>", html);
        Assert.Contains("body { color: red; }", html);
        Assert.Contains("<\\/style>", html);
        Assert.DoesNotContain("Generated:", html);
        Assert.DoesNotContain("</style><script>", html);
    }

    [Fact]
    public void ToHtml_renders_an_explicit_empty_state_for_an_empty_map()
    {
        string html = MetricsExporter.ToHtml(
            new Dictionary<string, string>(),
            new MetricsExportOptions { IncludeTimestamp = false });

        Assert.Contains("No metric data.", html);
    }

    [Fact]
    public void ToHtml_uses_the_default_options_when_none_are_given()
    {
        string html = MetricsExporter.ToHtml(new Dictionary<string, string>());

        Assert.Contains("<title>ArchUnitSharp Metrics Report</title>", html);
        Assert.Contains("Generated:", html);
    }

    [Fact]
    public void ToHtml_rejects_a_null_data_map()
    {
        Assert.Throws<ArgumentNullException>(() => MetricsExporter.ToHtml(null!));
    }

    [Fact]
    public void ExportAsHtml_creates_the_output_directory_and_writes_the_report()
    {
        using var dir = new TempDir();
        string path = System.IO.Path.Combine(dir.Path, "nested", "report.html");
        var data = new Dictionary<string, string> { ["method count [App.Car]"] = "1" };
        var options = new MetricsExportOptions { IncludeTimestamp = false, Title = "Counts" };

        string written = MetricsExporter.ExportAsHtml(data, path, options);

        Assert.Equal(path, written);
        Assert.True(File.Exists(path));
        Assert.Equal(MetricsExporter.ToHtml(data, options), File.ReadAllText(path));
    }

    [Fact]
    public void ExportAsHtml_rejects_a_null_or_empty_path()
    {
        Assert.Throws<ArgumentNullException>(() =>
            MetricsExporter.ExportAsHtml(new Dictionary<string, string>(), null!));
        Assert.Throws<ArgumentException>(() =>
            MetricsExporter.ExportAsHtml(new Dictionary<string, string>(), ""));
    }

    [Fact]
    public void ExportAsHtml_wraps_a_write_failure_in_a_technical_error()
    {
        using var dir = new TempDir();
        Assert.Throws<TechnicalError>(() =>
            MetricsExporter.ExportAsHtml(new Dictionary<string, string>(), dir.Path));
    }
}
