namespace ArchUnitSharp.Metrics.Rendering;

using System.Text;
using ArchUnitSharp.Metrics;

/// <summary>
/// The metrics module's pure HTML renderer: turns a metrics data map — one metric/subject pair per
/// value, as the count, cohesion and distance reports build it — into a self-contained HTML page with
/// every style inline, so the page renders the measurements in any browser with no script, no external
/// stylesheet and no network access. This is the module's one place a data map becomes HTML.
/// </summary>
/// <remarks>
/// <para>
/// The page is a two-column table of the data map, one row per entry in key order, beneath the title
/// and an optional timestamp. The title comes from the options bag; the timestamp is a pre-formatted
/// UTC instant the caller supplies — this renderer never reads the clock, so it is pure and
/// deterministic. The default stylesheet is the options bag's <see cref="MetricsExportOptions.CustomCss"/>
/// when one is given, otherwise a fixed built-in stylesheet.
/// </para>
/// <para>
/// Every key and value is routed through HTML escaping, so a metric name or measurement that contains
/// a character the browser parses cannot escape its table cell, and every <c>&lt;/style</c> sequence in
/// a custom stylesheet is neutralised so a stylesheet cannot close the style element and inject markup.
/// A data map with no entries renders an explicit <c>No metric data.</c> row, so an empty report is
/// visible data rather than a silently blank page. The output is stable and reproducible: rows are
/// always in sorted key order, whatever order the map itself yields.
/// </para>
/// <para>
/// This type is stateless and safe for concurrent use.
/// </para>
/// </remarks>
internal static class MetricsHtmlRenderer
{
    private const string DefaultCss =
        ":root { color-scheme: light dark; font-family: system-ui, sans-serif; }\n"
        + "body { max-width: 960px; margin: 0 auto; padding: 2rem; }\n"
        + "h1 { margin-bottom: .25rem; }\n"
        + ".timestamp { color: #666; margin-top: 0; }\n"
        + "table { border-collapse: collapse; margin-top: 1.5rem; width: 100%; }\n"
        + "th, td { border: 1px solid #bbb; padding: .6rem .8rem; text-align: left; }\n"
        + "th { background: rgba(127, 127, 127, .14); }\n"
        + "tr:nth-child(even) { background: rgba(127, 127, 127, .07); }\n"
        + "footer { color: #666; font-size: .85rem; margin-top: 2rem; }";

    /// <summary>
    /// Renders <paramref name="data"/> as a self-contained HTML page. The title and stylesheet come
    /// from <paramref name="options"/>; <paramref name="timestamp"/> is the pre-formatted UTC instant
    /// to show as the page's <c>Generated:</c> line, or <see langword="null"/> to omit the line.
    /// </summary>
    /// <param name="data">The metrics data map to render. Must not be <see langword="null"/>.</param>
    /// <param name="options">The report's options. Must not be <see langword="null"/>.</param>
    /// <param name="timestamp">The timestamp to show, or <see langword="null"/> for none.</param>
    /// <returns>The HTML document.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="data"/> or <paramref name="options"/> is <see langword="null"/>.</exception>
    public static string Render(
        IReadOnlyDictionary<string, string> data,
        MetricsExportOptions options,
        string? timestamp)
    {
        ArgumentNullException.ThrowIfNull(data);
        ArgumentNullException.ThrowIfNull(options);

        string title = Escape(options.Title);
        string css = SafeCss(options.CustomCss ?? DefaultCss);

        var builder = new StringBuilder();
        builder.Append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
        builder.Append("<meta charset=\"utf-8\">\n");
        builder.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
        builder.Append("<title>");
        builder.Append(title);
        builder.Append("</title>\n<style>");
        builder.Append(css);
        builder.Append("</style>\n</head>\n<body>\n<main>\n<h1>");
        builder.Append(title);
        builder.Append("</h1>\n");
        if (timestamp is not null)
        {
            builder.Append("<p class=\"timestamp\">Generated: ");
            builder.Append(Escape(timestamp));
            builder.Append("</p>\n");
        }

        builder.Append("<table>\n<thead><tr><th>Metric</th><th>Value</th></tr></thead>\n<tbody>\n");
        AppendRows(builder, data);
        builder.Append("</tbody>\n</table>\n</main>\n<footer>Generated by ArchUnitSharp</footer>\n</body>\n</html>\n");
        return builder.ToString();
    }

    /// <summary>
    /// Appends the data map's rows to <paramref name="builder"/>: one row per entry in sorted key
    /// order, or a single <c>No metric data.</c> row when the map is empty.
    /// </summary>
    private static void AppendRows(StringBuilder builder, IReadOnlyDictionary<string, string> data)
    {
        if (data.Count == 0)
        {
            builder.Append("<tr><td colspan=\"2\">No metric data.</td></tr>\n");
            return;
        }

        foreach (KeyValuePair<string, string> row in data.OrderBy(static pair => pair.Key, StringComparer.Ordinal))
        {
            builder.Append("<tr><td>");
            builder.Append(Escape(row.Key));
            builder.Append("</td><td>");
            builder.Append(Escape(row.Value));
            builder.Append("</td></tr>\n");
        }
    }

    /// <summary>
    /// Neutralises a stylesheet's <c>&lt;/style</c> sequences so it cannot close the style element and
    /// inject markup: every occurrence, case-insensitively, becomes <c>&lt;\/style</c>.
    /// </summary>
    private static string SafeCss(string css) =>
        css.Replace("</style", "<\\/style", StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Escapes a value as text inside an HTML element: the five characters a browser parses —
    /// <c>&amp;</c>, <c>&lt;</c>, <c>&gt;</c>, <c>&quot;</c> and <c>&#39;</c> — become their entities.
    /// </summary>
    private static string Escape(string value) =>
        value.Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal)
            .Replace("\"", "&quot;", StringComparison.Ordinal)
            .Replace("'", "&#39;", StringComparison.Ordinal);
}
